name: Generate Projects And Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Generate all defined projects
        run: mvn clean --batch-mode --update-snapshots verify # use verify to run integration tests of maven plugin
      - name: Build generated projects
        run: for project in ./kie-assets-library-generate/target/*/pom.xml; do mvn clean package -f $project; done
